apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: square-app
  name: square-app
spec:
  replicas: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: square-app
  template:
    metadata:
      labels:
        app: square-app
    spec:
      containers:
      - image: guyeise5/square-app:latest
        name: square-app
        ports:
        - containerPort: 8080
        env:
          - name: MY_COLOR
            value: "red"
        readinessProbe:
          initialDelaySeconds: 5
          failureThreshold: 1
          httpGet:
            port: 8080
            path: /health/ready
