apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manager
spec:
  rules:
  - host: square-app.test
    http:
      paths:
      - backend:
          service:
            name: square-app
            port:
              name: web
        path: /
        pathType: Prefix
